---
- name: "test de la solution drupal"
  hosts: all
  gather_facts: true
  tasks:
    - name: "debut du test"
      debug:
        msg: "Voici le debut du test"
    -  set_fact:
        ipadd: "{{ ansible_default_ipv4.address }}"
    -  debug:
        msg: "http://{{ ipadd }}"

