---
- name: "test de la solution drupal"
  hosts: all
  gather_facts: True
  tasks:
    - set_fact:
        ipadd: "{{ ansible_default_ipv4.address }}"
    - name: "get homepage HTTP code"
      uri:
        url: "http://{{ ipadd }}"
