---
- name: "test de  la solution drupal"
  hosts: all
  gather_facts: True 
  tasks:
          - set_fact:
              ipadd: "{{ ansible_default_ipv4.address }}"
          - name: "début du test"
            debug:
              msg: "voici le début du test"
          - name: "contenu de la page Drupal"
            uri:
              url: "http://{{ ipadd }}"
              return_content: yes
            register: output
          - debug:
              msg: "Drupal OK"
            when: output.content is search ("Powered by")

          
