---
- name: "Test de la solution Drupal"
  hosts: all
  gather_facts: True
  tasks:
    - name: "Début du test"
      debug:
        msg: "Voici le début du test"
        #    - name: "Get homepage HTTP code"
        #      uri:
        #        url: http://127.0.0.1
    - debug: var=ansible_all_ipv4_addresses
    - set_fact:
        ipadd0: "{{ ansible_all_ipv4_addresses[0] }}"
        ipadd: "{{ ansible_default_ipv4.address }}"
    - name: "Get homepage HTTP code"
      uri:
        url: "http://{{ipadd}}"
