---
- name: "print ipv4 public address"
  hosts: all
  gather_facts: True
  tasks:
    - set_fact:
        ip: "{{ansible_all_ipv4_addresses[0]}}"
    - debug:
        msg: "http://{{ip}}"
    - uri:
        url: "http://{{ip}}"
        return_content: yes
      register: output
    - debug:
        msg: "drupal OK"
      when: output.content is search("Powered by")
      #failed_when: output.content is search("Powered by")
