---
- name: "test de  la solution drupal"
  hosts: all
  gather_facts: True 
  tasks:
          - set_fact:
             ipadd: "{{ ansible_default_ipv4.address }}"

          - name: "début du test"
            debug:
             msg: "voici le début du test"

             # - name: "get homepage HTTP code"
             #uri:
          - debug:
              msg: "http://{{ ipadd }}"
            #debug: var=ansible_virtualization_type
