---
- name: test de la solution drupal
  hosts: all
  gather_facts: true
  tasks:
    - name: debut du test
      debug:
        msg: "voici le début du test"
    - name:  "get distribution vm"
      debug: 
        msg: "mon system d'exploitation est {{ ansible_distribution }} " 
