---
- name: "récupérer l'adresse IP en tant que fact"
  hosts: drupal01
  gather_facts: True
  tasks:
    - uri:
        url: https://ipinfo.io/ip
        return_content: yes
      register: output
    - set_fact:
            ip_adress: "{{ output.content | replace('\n', '') }}"
    - debug:
        msg: "{{ip_adress}}"

