---
- name: "test de la solution drupal"
  hosts: all
  gather_facts: true
  tasks:
    - name: "debut du test"
      debug:
        msg: "voici le debut du test"
    - name: "get homepage HTTP code"
      uri:
        url: http://127.0.0.1       
