---
- name: "test de la solution drupal"
  hosts: all
  gather_facts: True
  tasks: 
    - name: "début du test"
      debug: 
        msg: "voici le début du test"
    - name: "voir la page d'accueil"

