---
- name: "test de la solution drupal"
  hosts: all
  gather_facts: true
  tasks:
    - name: "debut du test"
      debug:
        msg: "Voici le debut du test"
    -  set_fact:
        ipadd: "{{ ansible_default_ipv4.address }}"
    -  debug: 
        msg: "http://{{ ipadd }}"
    - uri:
        url: "http://{{ ipadd }}"
        return_content: yes
      register: output
    - debug:
        msg: "Drupal OK"
      when: output.content is search("Powered by")
      failed_when: output.content is not search('assane')
