---
- hosts: all
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
  tasks:
    - name: Enable Apache rewrite module (required for Drupal).
      apache2_module: name=rewrite state=present
      notify: restart apache  
